name: Deploy NuGet Package

env:
  DOCKER_PROJECT_DIR: .
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          VERSION=${{  github.ref_name }}
          echo "VERSION=${VERSION/v/}" >> $GITHUB_ENV
      - uses: docker/setup-qemu-action@v1
        with:
          platforms: "amd64,arm64"
      - uses: docker/setup-buildx-action@v1
        id: buildx
      - uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner  }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
      - uses: docker/build-push-action@v2
        with:
          build-args: VERSION=${{ env.VERSION }}
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ env.DOCKER_PROJECT_DIR }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}